name: Deploy to Server

on:
  push:
    branches:
      - main  # یا branch موردنظر

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/html/portfolio/
            git stash
            git pull origin main
            php artisan migrate:fresh --seed

            # ✅ Fix permissions
            chown -R www-data:www-data storage
            chown -R www-data:www-data bootstrap/cache

            # 📦 Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # 🧰 Build frontend
            npm install
            npm run build

            composer update
            npm run build
            # 🔧 Laravel caches
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
          EOF
